apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-devops
  namespace: haproxy-controller-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ingress-default-backend
  template:
    spec:
      containers:
        - name: backend-container-devops
          image: gcr.io/google_containers/defaultbackend:1.0
          ports:
            - containerPort: 8080
    metadata:
      name: backend-pod-devops
      labels:
        run: ingress-default-backend


