apiVersion: v1
kind: Service
metadata:
  name: service-backend-devops
  namespace: haproxy-controller-devops
spec:
  selector:
    run: ingress-default-backend
  ports:
  - port: 80
    targetPort: 8080