apiVersion: v1
kind: Service
metadata:
  name: ingress-service-devops
  namespace: haproxy-controller-devops
spec:
  type: NodePort
  selector:
    run: haproxy-ingress
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32456
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
      nodePort: 32567
    - name: stat
      port: 1024
      targetPort: 1024
      protocol: TCP
      nodePort: 32678