apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
spec:
  replicas: 3
  template:
    metadata:
      name: busybox-pod
      labels:
        label: busybox-label
    spec:
      containers:
        - name: busybox
          image: nginx
  selector:
    matchLabels:
      label: busybox-label
