apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
    - name: db-container
      image: mysql:5.7
      ports:
        - containerPort: 3306
      envFrom:
        - secretRef:
           name: db-secret
