apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-conf
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-config