apiVersion: v1
kind: Pod
metadata:
 name: webapp
spec:
 containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
      - mountPath: /var/log/nginx
        name: cache-volume

 volumes:
  - name: cache-volume
    persistentVolumeClaim:
      claimName: claim-log-1