apiVersion: v1
kind: Pod
metadata:
 name: volume-share-datacenter
spec:
 containers:
  - image: centos:latest
    name: volume-container-datacenter-1
    command: [ '/bin/bash', '-c' ]
    args: ["sleep 10000"]
    volumeMounts:
      - mountPath: /tmp/news
        name: volume-share
  
  - image: centos:latest
    name: volume-container-datacenter-2
    command: [ '/bin/bash', '-c' ]
    args: ["sleep 10000"]
    volumeMounts:
      - mountPath: /tmp/cluster
        name: volume-share

 volumes:
  - name: volume-share
    emptyDir: {}