apiVersion: v1
kind: Pod
metadata:
 name: webserver
spec:
 containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
      - mountPath: /var/log/nginx
        name: shared-logs

  - image: ubuntu:latest
    name: sidecar-container
    command: [ "sh", "-c" ]
    args : ["while true; do cat /var/log/nginx/access.log 
/var/log/nginx/error.log; sleep 30; done"]
    volumeMounts:
      - mountPath: /var/log/nginx
        name: shared-logs

 volumes:
  - name: shared-logs
    emptyDir: {}