apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-statefulset
spec:
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        tag: nginx
    spec:
      containers:
        - name : nginx-container
          image: nginx
  selector:
    matchLabels:
      tag: nginx
