apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      name: nginx-pod
      labels:
        tier: nginx
    spec:
      containers:
        - name: web-app
          image: nginx
