apiVersion: v1
kind: Pod
metadata:
  name: tolerant-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key : special-node
      operator: Equal
      value: "true"
      effect:  NoSchedule
