apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
  namespace: finance
spec:
  replicas: 2
  template:
    metadata:
      name: redis-pod 
      labels:
        tag: redis
    spec:
      containers:
        - name: redis-container
          image: redis
          resources:
            requests:
              memory: 1G 
              cpu: 500m
            limits:
              memory: 2G
              cpu: 1
  selector:
    matchLabels:
      tag: redis
