apiVersion: apps/v1
kind: Deployment
metadata:
  name : nginx
  namespace: iti
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        tag: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      tag: nginx
    
